import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import DropDownMenu from "../components/DropDownMenu";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>ל.א.ו</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div>
        <Image
          className={styles.mainImg}
          src="/newHomePic.png"
          alt=""
          width={1700}
          height={600}
        />
      </div>
      <div
        className={styles.aboutDiv}
        style={{ fontFamily: "Open Sans Hebrew Condensed" + "serif" }}
      >
        <Link href="/about">
          <div className={styles.bottomLink}>
            <p>
              ל.א.ו הוא ארגון ללא מטרות רווח שהוקם
              <br />
              כדי ליצור אחדות בעם ישראל בעזרת נתינה לאחר
              <br />
              <br /> <span>לחצו כאן לסיפור המלא שלנו</span>
            </p>
          </div>
        </Link>
      </div>
    </div>
  );
}
